# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tender_Notice_Type', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Category', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('Deadline', models.CharField(max_length=250)),
                ('Ref', models.CharField(max_length=250)),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
    ]
