# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Ref',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
